defmodule EmojiLife.Game.Implementations.ClassicTest do
  use ExUnit.Case

  alias EmojiLife.Game
  alias EmojiLife.Game.Implementations

  describe "basic step" do
    {:ok, start} = Game.board_from_string("""
      ........
      ....*...
      ...**...
      ........
    """)
    {:ok, expected} = Game.board_from_string("""
      ........
      ...**...
      ...**...
      ........
    """)

    {:ok, actual} = Implementations.Classic.step(start)
    assert actual == expected
  end

  describe "complicated step" do
    {:ok, start} = Game.board_from_string("""
      ..........
      ...**.....
      ....*.....
      ..........
      ..........
      ...**.....
      ..**......
      .....*....
      ....*.....
      ..........
    """)

    {:ok, expected} = Game.board_from_string("""
      ..........
      ...**.....
      ...**.....
      ..........
      ..........
      ..***.....
      ..**......
      ...**.....
      ..........
      ..........
    """)

    {:ok, actual} = Implementations.Classic.step(start)
    assert actual == expected
  end

  describe "different cells" do
    {:ok, start} = Game.board_from_string("""
      ..++....
      ....*...
      ...*+...
      ........
    """)
    {:ok, expected} = Game.board_from_string("""
      ..++....
      ...+*...
      ...*+...
      ........
    """)

    {:ok, actual} = Implementations.Classic.step(start)
    assert actual == expected
  end

end
